---
# tasks file for docker-host
- name: Add Docker package signing key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Docker apt package
  become: true
  apt:
    name: "docker-{{ docker.edition }}"
    state: present

- name: Setup Docker daemon
  become: true
  service:
    name: docker
    state: "{% if docker.daemon is defined and docker.daemon %} started {% else %} stopped {% endif %}"
    enabled: "{% if docker.daemon is defined and docker.daemon %} yes {% else %} no {% endif %}"
